# -*- coding: utf-8 -*-
"""TASK--1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CjoMftQHy1XAI0ghYzqHsB7wzNk6eC4U
"""

import pandas as pd
df=pd.read_csv('/content/sample_data/SALESDS.csv')
df

import pandas as pd
df2 = df.drop_duplicates()

print("\nDataset after Removing Duplicates:")
print(df2)

print("\nMissing Value Count per Column:")
print(df.isnull().sum())

import pandas as pd
df_filled=df.fillna({
    'Sales_Amount':df['Sales_Amount'].mean(),
    'Units_Cost':'00.0'

})
print("\nDataset after Filling Missing Values:")
print(df_filled)

df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

print(df.columns)

